import { Product } from '../domain/product';

export const products: Product[] = [
  {
    id: '1',
    title: 'iPhone 13 Pro',
    description: 'Apple iPhone 13 Pro with A15 Bionic chip',
    price: 999,
    count: 50,
    imgUrl: 'https://w7.pngwing.com/pngs/486/588/png-transparent-iphone-13-pro-back.png',
  },
  {
    id: '2',
    title: 'Samsung Galaxy S21',
    description: 'Samsung Galaxy S21 with Exynos 2100',
    price: 799,
    count: 30,
    imgUrl:
      'https://w7.pngwing.com/pngs/108/8/png-transparent-samsung-galaxy-s21-ultra-electronics-android-phones-thumbnail.png',
  },
  {
    id: '3',
    title: 'Google Pixel 6',
    description: 'Google Pixel 6 with Google Tensor chip',
    price: 599,
    count: 20,
    imgUrl: 'https://storage.googleapis.com/alpine-inkwell-325917.appspot.com/devices/pixel-6-header.png',
  },
  {
    id: '4',
    title: 'OnePlus 9 Pro',
    description: 'OnePlus 9 Pro with Snapdragon 888',
    price: 969,
    count: 25,
    imgUrl:
      'https://oasis.opstatics.com/content/dam/oasis/page/2021/9-series/spec-image/9-pro/Morning%20mist-gallery.png',
  },
  {
    id: '5',
    title: 'Xiaomi Mi 11',
    description: 'Xiaomi Mi 11 with Snapdragon 888',
    price: 749,
    count: 40,
    imgUrl: 'https://w7.pngwing.com/pngs/30/981/png-transparent-redmi-note-11s.png',
  },
  {
    id: '6',
    title: 'Sony Xperia 1 III',
    description: 'Sony Xperia 1 III with Snapdragon 888',
    price: 1199,
    count: 15,
    imgUrl:
      'https://www.notebookcheck.net/fileadmin/Notebooks/Sony/Xperia_1_III/4_zu_3_Sony_Xperia_1_III_bearbeitet_1.jpg',
  },
  {
    id: '7',
    title: 'Oppo Find X3 Pro',
    description: 'Oppo Find X3 Pro with Snapdragon 888',
    price: 1149,
    count: 10,
    imgUrl: 'https://image.oppo.com/content/dam/oppo/product-asset-library/find/fussi/2116x1668.png',
  },
  {
    id: '8',
    title: 'Huawei P50 Pro',
    description: 'Huawei P50 Pro with Kirin 9000',
    price: 1099,
    count: 5,
    imgUrl:
      'https://consumer.huawei.com/content/dam/huawei-cbg-site/common/mkt/pdp/phones/p50-pro/images/design/color/black.png',
  },
  {
    id: '9',
    title: 'Asus ROG Phone 5',
    description: 'Asus ROG Phone 5 with Snapdragon 888',
    price: 999,
    count: 18,
  },
  {
    id: '10',
    title: 'Realme GT',
    description: 'Realme GT with Snapdragon 888',
    price: 499,
    count: 35,
  },
  {
    id: '11',
    title: 'Vivo X60 Pro',
    description: 'Vivo X60 Pro with Snapdragon 870',
    price: 699,
    count: 22,
  },
  {
    id: '12',
    title: 'Nokia 8.3 5G',
    description: 'Nokia 8.3 5G with Snapdragon 765G',
    price: 599,
    count: 28,
  },
  {
    id: '13',
    title: 'Motorola Edge 20 Pro',
    description: 'Motorola Edge 20 Pro with Snapdragon 870',
    price: 699,
    count: 12,
  },
  {
    id: '14',
    title: 'LG Wing',
    description: 'LG Wing with Snapdragon 765G',
    price: 999,
    count: 8,
  },
  {
    id: '15',
    title: 'ZTE Axon 30 Ultra',
    description: 'ZTE Axon 30 Ultra with Snapdragon 888',
    price: 749,
    count: 14,
  },
  {
    id: '16',
    title: 'Lenovo Legion Phone Duel 2',
    description: 'Lenovo Legion Phone Duel 2 with Snapdragon 888',
    price: 899,
    count: 9,
  },
  {
    id: '17',
    title: 'Honor 50 Pro',
    description: 'Honor 50 Pro with Snapdragon 778G',
    price: 599,
    count: 20,
  },
  {
    id: '18',
    title: 'Meizu 18 Pro',
    description: 'Meizu 18 Pro with Snapdragon 888',
    price: 799,
    count: 15,
  },
  {
    id: '19',
    title: 'Redmi Note 10 Pro',
    description: 'Redmi Note 10 Pro with Snapdragon 732G',
    price: 299,
    count: 50,
  },
  {
    id: '20',
    title: 'Poco F3',
    description: 'Poco F3 with Snapdragon 870',
    price: 399,
    count: 45,
  },
  {
    id: '21',
    title: 'Vivo V21',
    description: 'Vivo V21 with MediaTek Dimensity 800U',
    price: 349,
    count: 30,
  },
  {
    id: '22',
    title: 'Realme 8 Pro',
    description: 'Realme 8 Pro with Snapdragon 720G',
    price: 279,
    count: 40,
  },
  {
    id: '23',
    title: 'Samsung Galaxy A52',
    description: 'Samsung Galaxy A52 with Snapdragon 720G',
    price: 349,
    count: 35,
  },
  {
    id: '24',
    title: 'OnePlus Nord 2',
    description: 'OnePlus Nord 2 with MediaTek Dimensity 1200',
    price: 399,
    count: 25,
  },
  {
    id: '25',
    title: 'Xiaomi Mi 11 Lite',
    description: 'Xiaomi Mi 11 Lite with Snapdragon 732G',
    price: 299,
    count: 40,
  },
  {
    id: '26',
    title: 'Sony Xperia 10 III',
    description: 'Sony Xperia 10 III with Snapdragon 690',
    price: 429,
    count: 18,
  },
  {
    id: '27',
    title: 'Oppo Reno6 Pro',
    description: 'Oppo Reno6 Pro with MediaTek Dimensity 1200',
    price: 499,
    count: 22,
  },
  {
    id: '28',
    title: 'Huawei Nova 8',
    description: 'Huawei Nova 8 with Kirin 820E',
    price: 399,
    count: 30,
  },
  {
    id: '29',
    title: 'Asus Zenfone 8',
    description: 'Asus Zenfone 8 with Snapdragon 888',
    price: 699,
    count: 15,
  },
  {
    id: '30',
    title: 'Nokia G50',
    description: 'Nokia G50 with Snapdragon 480',
    price: 299,
    count: 25,
  },
];
