openapi: 3.0.0
info:
  title: Products API
  version: 1.0.0
  description: API documentation for the Products service
servers:
  - url: https://p96ay8o36j.execute-api.eu-central-1.amazonaws.com/prod
    variables:
      restapi_id:
        default: v1
      region:
        default: eu-central-1
      stage:
        default: dev
paths:
  /products:
    get:
      summary: Get list of products
      operationId: getProductsList
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
  /products/{id}:
    get:
      summary: Get product by ID
      operationId: getProductsById
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The product ID
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Product not found
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
          nullable: true
        price:
          type: number
        count:
          type: integer
        imgUrl:
          type: string
          nullable: true
      required:
        - id
        - title
        - price
        - count
