openapi: 3.0.0
info:
  title: Products API
  version: 1.0.0
  description: API documentation for the Products service
servers:
  - url: https://luwm75ht9a.execute-api.eu-central-1.amazonaws.com/prod/products
    variables:
      restapi_id:
        default: v1
      region:
        default: eu-central-1
      stage:
        default: dev
paths:
  /products:
    get:
      summary: Get list of products
      operationId: getProductsList
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      summary: Create a new product
      operationId: createProduct
      requestBody:
        description: Product to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProductRequestDto'
      responses:
        '201':
          description: Product created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductWithStock'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid body
  /products/{id}:
    get:
      summary: Get product by ID
      operationId: getProductsById
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The product ID
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductWithStock'
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Product {productId} not found
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
          nullable: true
        price:
          type: number
      required:
        - id
        - title
        - price
    Stock:
      type: object
      properties:
        product_id:
          type: string
        count:
          type: number
      required:
        - product_id
        - count
    CreateProductRequestDto:
      type: object
      properties:
        title:
          type: string
        price:
          type: number
        description:
          type: string
          nullable: true
        count:
          type: number
      required:
        - title
        - price
        - count
    ProductWithStock:
      allOf:
        - $ref: '#/components/schemas/Product'
        - type: object
          properties:
            count:
              type: number
