openapi: 3.0.0
info:
  title: Import API
  version: 1.0.0
  description: API documentation for the Import service
servers:
  - url: https://xt3lx7qwli.execute-api.eu-central-1.amazonaws.com/prod/import
paths:
  /:
    get:
      summary: Get s3 signed url for uploading a csv file with products
      operationId: importProductsFileTest
      parameters:
        - in: query
          name: name
          required: true
          schema:
            type: string
          description: The name of the file to be uploaded
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string
                    example: https://presignedurldemo.s3.eu-west-2.amazonaws.com/image.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAJJWZ7B6WCRGMKFGQ%2F20180210%2Feu-west-2%2Fs3%2Faws4_request&X-Amz-Date=20180210T171315Z&X-Amz-Expires=1800&X-Amz-Signature=12b74b0788aa036bc7c3d03b3f20c61f1f91cc9ad8873e3314255dc479a25351&X-Amz-SignedHeaders=host
        '400':
          description: File name missing
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Empty file name
